// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4-RW3Jw9G-JG0YDrFSzaVZuArDiO56mw',
    appId: '1:568849569407:web:35b827e547bffc5485114a',
    messagingSenderId: '568849569407',
    projectId: 'rgt-pulse',
    authDomain: 'rgt-pulse.firebaseapp.com',
    storageBucket: 'rgt-pulse.appspot.com',
    measurementId: 'G-T5YCTL1PKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmuF6H5Ot_4LafbOoplGjKUB2AYPPpGXU',
    appId: '1:568849569407:android:89893d15d97413ea85114a',
    messagingSenderId: '568849569407',
    projectId: 'rgt-pulse',
    storageBucket: 'rgt-pulse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUSQfGlrUqD9rrtN14EoCBufsKDPCC19w',
    appId: '1:568849569407:ios:483bd987cbb9563085114a',
    messagingSenderId: '568849569407',
    projectId: 'rgt-pulse',
    storageBucket: 'rgt-pulse.appspot.com',
    iosBundleId: 'com.example.rgtPulse',
  );
}
